language: generic 
notifications: 
  email: false
sudo: required
services:
  - docker

before_install:
  - docker build -t docker141199/docker-react -f Dockerfile.dev .

sript:
   - docker run -e CI=true docker141199/docker-react npm run test
