language: generic 
notifications: 
  email: false
sudo: required
services:
  - docker

before_install:
  - docker build -t docker141199/docker-react -f Dockerfile.dev .

sript:
   - docker run -e CI=true docker141199/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-126892455341"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


  